# Generated by Django 3.2.16 on 2026-04-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='leadership_style',
            field=models.CharField(blank=True, choices=[('authoritarian', 'Авторитарный'), ('democratic', 'Демократический'), ('coaching', 'Коучинг'), ('delegating', 'Делегирующий')], max_length=50, null=True, verbose_name='Стиль управления'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='disc_profile',
            field=models.JSONField(blank=True, help_text='{"D": 80, "I": 40, "S": 30, "C": 60}', null=True, verbose_name='DISC профиль руководителя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='generation',
            field=models.CharField(blank=True, choices=[('X', 'Поколение X (1965–1980)'), ('Y', 'Поколение Y / Миллениалы (1981–1996)'), ('Z', 'Поколение Z (1997–2012)'), ('Alpha', 'Поколение Alpha (2013+)')], max_length=10, null=True, verbose_name='Поколение'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gerchikov_type',
            field=models.CharField(blank=True, choices=[('instrumental', 'Инструментальный (деньги / результат)'), ('professional', 'Профессиональный (рост / мастерство)'), ('patriotic', 'Патриотический (причастность / команда)'), ('administrative', 'Административный (статус / стабильность)'), ('master', 'Хозяйский (автономия / ответственность)'), ('mixed', 'Смешанный')], max_length=50, null=True, verbose_name='Тип мотивации по Герчикову'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role_style',
            field=models.TextField(blank=True, verbose_name='Описание стиля управления'),
        ),
    ]
