# Generated by Django 3.2.16 on 2026-04-17 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdealProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=100, verbose_name='Целевая роль')),
                ('disc_preferred', models.JSONField(verbose_name='Желаемый DISC')),
                ('gerchikov_preferred', models.CharField(blank=True, choices=[('instrumental', 'Инструментальный (деньги)'), ('professional', 'Профессиональный'), ('patriotic', 'Патриотический'), ('administrative', 'Административный'), ('master', 'Хозяйский'), ('mixed', 'Смешанный')], max_length=50, null=True, verbose_name='Предпочитаемый тип мотивации по Герчикову')),
                ('age_range', models.JSONField(help_text='{"min": 25, "max": 45}', verbose_name='Диапазон возраста')),
                ('generation_preferred', models.CharField(blank=True, choices=[('X', 'X'), ('Y', 'Y'), ('Z', 'Z'), ('Alpha', 'Alpha')], max_length=10, null=True, verbose_name='Предпочитаемое поколение')),
                ('motivation_style', models.TextField(verbose_name='Стиль мотивации')),
                ('team_compatibility_note', models.TextField(blank=True, verbose_name='Особые требования к команде')),
                ('is_for_existing_team', models.BooleanField(default=False, verbose_name='Для существующего состава')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideal_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.employee')),
                ('ideal_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.idealprofile')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score'],
            },
        ),
    ]
