# Generated by Django 3.2.16 on 2026-04-17 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idealprofile',
            options={'verbose_name': 'Идеальный профиль', 'verbose_name_plural': 'Идеальные профили'},
        ),
        migrations.AlterModelOptions(
            name='recommendationlog',
            options={'ordering': ['-match_score', '-created_at'], 'verbose_name': 'Лог рекомендации', 'verbose_name_plural': 'Логи рекомендаций'},
        ),
        migrations.RemoveField(
            model_name='recommendationlog',
            name='explanation',
        ),
        migrations.AddField(
            model_name='idealprofile',
            name='preferred_personality_types',
            field=models.JSONField(default=list, help_text='Например: ["S", "C"] — спокойные и исполнительные, или ["I", "D"] — активные и напористые', verbose_name='Предпочитаемые типы личности'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий руководителя'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='fits_manager_style',
            field=models.BooleanField(default=False, verbose_name='Хорошо подходит под мой стиль управления'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='motivation_match',
            field=models.BooleanField(default=False, verbose_name='Мотивация совпадает'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='potential_issues',
            field=models.TextField(blank=True, verbose_name='Возможные риски / минусы'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='productive',
            field=models.BooleanField(default=False, verbose_name='Продуктивный / даёт результат'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='status',
            field=models.CharField(choices=[('taken', 'Взят в команду'), ('good', 'Хороший кандидат'), ('average', 'Средний кандидат'), ('rejected', 'Отклонён'), ('none', 'Без оценки')], default='none', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='works_well_in_team',
            field=models.BooleanField(default=False, verbose_name='Хорошо работает в команде'),
        ),
        migrations.AlterField(
            model_name='idealprofile',
            name='disc_preferred',
            field=models.JSONField(help_text='{"D": 70, "I": 80, "S": 40, "C": 30} — насколько каждый тип желателен (0-100)', verbose_name='Желаемый DISC профиль'),
        ),
        migrations.AlterField(
            model_name='idealprofile',
            name='is_for_existing_team',
            field=models.BooleanField(default=False, verbose_name='Рекомендации для существующего состава команды'),
        ),
        migrations.AlterField(
            model_name='idealprofile',
            name='motivation_style',
            field=models.TextField(blank=True, verbose_name='Желаемый стиль мотивации (премии, развитие, стабильность и т.д.)'),
        ),
        migrations.AlterField(
            model_name='idealprofile',
            name='target_role',
            field=models.CharField(max_length=100, verbose_name='Целевая роль / позиция'),
        ),
        migrations.AlterField(
            model_name='idealprofile',
            name='team_compatibility_note',
            field=models.TextField(blank=True, verbose_name='Дополнительные пожелания к команде'),
        ),
        migrations.AlterField(
            model_name='recommendationlog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.employee', verbose_name='Рекомендованный сотрудник'),
        ),
        migrations.AlterField(
            model_name='recommendationlog',
            name='ideal_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.idealprofile', verbose_name='Идеальный профиль'),
        ),
        migrations.AlterField(
            model_name='recommendationlog',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='recommendationlog',
            name='match_score',
            field=models.FloatField(verbose_name='Процент совпадения'),
        ),
    ]
