# Generated by Django 3.2.16 on 2026-04-17 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20260418_0153'),
        ('recommendations', '0002_auto_20260417_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idealprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Идеальный профиль', 'verbose_name_plural': 'Идеальные профили'},
        ),
        migrations.RemoveField(
            model_name='idealprofile',
            name='age_range',
        ),
        migrations.AddField(
            model_name='idealprofile',
            name='age_max',
            field=models.PositiveIntegerField(default=50, verbose_name='Возраст до'),
        ),
        migrations.AddField(
            model_name='idealprofile',
            name='age_min',
            field=models.PositiveIntegerField(default=20, verbose_name='Возраст от'),
        ),
        migrations.AddField(
            model_name='idealprofile',
            name='leadership_style',
            field=models.CharField(choices=[('authoritarian', 'Авторитарный — чёткие задачи, контроль'), ('democratic', 'Демократический — обсуждение, команда'), ('coaching', 'Коучинг — развитие, поддержка'), ('delegating', 'Делегирующий — автономия, результат')], default='democratic', max_length=50, verbose_name='Ваш стиль управления'),
        ),
        migrations.AddField(
            model_name='idealprofile',
            name='role_functions',
            field=models.JSONField(default=list, help_text="['sells', 'negotiates'] — что реально делает человек", verbose_name='Функции роли'),
        ),
        migrations.AddField(
            model_name='idealprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.team', verbose_name='Команда (если подбор в существующую)'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='score_breakdown',
            field=models.JSONField(default=dict, verbose_name='Детализация по осям'),
        ),
        migrations.AlterField(
            model_name='idealprofile',
            name='disc_preferred',
            field=models.JSONField(help_text='{"D": 70, "I": 80, "S": 40, "C": 30}', verbose_name='Желаемый DISC профиль'),
        ),
        migrations.AlterField(
            model_name='idealprofile',
            name='generation_preferred',
            field=models.CharField(blank=True, choices=[('X', 'Поколение X (1965–1980)'), ('Y', 'Поколение Y / Миллениалы (1981–1996)'), ('Z', 'Поколение Z (1997–2012)'), ('Alpha', 'Поколение Alpha (2013+)')], max_length=10, null=True, verbose_name='Предпочитаемое поколение'),
        ),
        migrations.AlterField(
            model_name='idealprofile',
            name='gerchikov_preferred',
            field=models.CharField(blank=True, choices=[('instrumental', 'Инструментальный (деньги / результат)'), ('professional', 'Профессиональный (рост / мастерство)'), ('patriotic', 'Патриотический (причастность / команда)'), ('administrative', 'Административный (статус / стабильность)'), ('master', 'Хозяйский (автономия / ответственность)'), ('mixed', 'Смешанный')], max_length=50, null=True, verbose_name='Предпочитаемый тип мотивации по Герчикову'),
        ),
        migrations.AlterField(
            model_name='idealprofile',
            name='is_for_existing_team',
            field=models.BooleanField(default=False, verbose_name='Подбор в существующую команду?'),
        ),
        migrations.AlterField(
            model_name='idealprofile',
            name='motivation_style',
            field=models.TextField(blank=True, verbose_name='Как планируете мотивировать сотрудника?'),
        ),
        migrations.AlterField(
            model_name='idealprofile',
            name='preferred_personality_types',
            field=models.JSONField(default=list, help_text='["S", "C"]', verbose_name='Предпочитаемые типы личности'),
        ),
        migrations.AlterField(
            model_name='idealprofile',
            name='target_role',
            field=models.CharField(max_length=200, verbose_name='Название роли / позиции'),
        ),
        migrations.AlterField(
            model_name='idealprofile',
            name='team_compatibility_note',
            field=models.TextField(blank=True, verbose_name='Дополнительные пожелания'),
        ),
        migrations.AlterField(
            model_name='recommendationlog',
            name='fits_manager_style',
            field=models.BooleanField(default=False, verbose_name='Подходит под стиль управления'),
        ),
        migrations.AlterField(
            model_name='recommendationlog',
            name='match_score',
            field=models.FloatField(verbose_name='Итоговый балл (0-100)'),
        ),
        migrations.AlterField(
            model_name='recommendationlog',
            name='potential_issues',
            field=models.TextField(blank=True, verbose_name='Риски / минусы'),
        ),
        migrations.AlterField(
            model_name='recommendationlog',
            name='productive',
            field=models.BooleanField(default=False, verbose_name='Продуктивный'),
        ),
    ]
