# Generated by Django 3.2.16 on 2026-04-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_auto_20260418_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationlog',
            name='match_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Итоговый балл (0-100)'),
        ),
    ]
