# Generated by Django 3.2.16 on 2026-04-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_alter_recommendationlog_match_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idealprofile',
            name='generation_preferred',
            field=models.CharField(blank=True, choices=[('X', 'Поколение X (1965–1980)'), ('BB', 'Бэби-бумеры (1944–1964)'), ('Y', 'Поколение Y / Миллениалы (1981–1996)'), ('Z', 'Поколение Z (1997–2012)'), ('Alpha', 'Поколение Alpha (2013+)')], max_length=10, null=True, verbose_name='Предпочитаемое поколение'),
        ),
    ]
