# Generated by Django 3.2.16 on 2026-04-19 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_alter_idealprofile_generation_preferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationlog',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка руководителя (1-5)'),
        ),
        migrations.AlterField(
            model_name='recommendationlog',
            name='ideal_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendations.idealprofile', verbose_name='Идеальный профиль'),
        ),
    ]
