# Generated by Django 3.2.16 on 2026-04-17 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название команды')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('is_active_candidate', models.BooleanField(default=True, verbose_name='Активный кандидат')),
                ('disc_scores', models.JSONField(help_text='{"D": 85, "I": 60, "S": 30, "C": 25}', verbose_name='DISC баллы')),
                ('gerchikov_type', models.CharField(choices=[('instrumental', 'Инструментальный (деньги)'), ('professional', 'Профессиональный'), ('patriotic', 'Патриотический'), ('administrative', 'Административный'), ('master', 'Хозяйский'), ('mixed', 'Смешанный')], max_length=50, verbose_name='Тип мотивации по Герчикову')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('generation', models.CharField(choices=[('X', 'X'), ('Y', 'Y'), ('Z', 'Z'), ('Alpha', 'Alpha')], max_length=10, verbose_name='Поколение')),
                ('role_in_team', models.CharField(max_length=100, verbose_name='Роль в команде')),
                ('salary_block', models.JSONField(help_text='{"min": 150000, "motivation": "премии", "development": "обучение"}', verbose_name='Блок зарплаты')),
                ('motivation_expect', models.TextField(verbose_name='Что хочет сотрудник')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('current_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='profiles.team')),
            ],
            options={
                'verbose_name': 'Сотрудник / Кандидат',
                'verbose_name_plural': 'Сотрудники / Кандидаты',
                'ordering': ['-is_active_candidate', 'fio'],
            },
        ),
    ]
