# Generated by Django 3.2.16 on 2026-04-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-created_at'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='disc_scores',
            field=models.JSONField(blank=True, help_text='{"D": 85, "I": 60, "S": 30, "C": 25}', null=True, verbose_name='DISC баллы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='generation',
            field=models.CharField(choices=[('X', 'Поколение X (1965–1980)'), ('Y', 'Поколение Y / Миллениалы (1981–1996)'), ('Z', 'Поколение Z (1997–2012)'), ('Alpha', 'Поколение Alpha (2013+)')], max_length=10, verbose_name='Поколение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gerchikov_type',
            field=models.CharField(choices=[('instrumental', 'Инструментальный (деньги / результат)'), ('professional', 'Профессиональный (рост / мастерство)'), ('patriotic', 'Патриотический (причастность / команда)'), ('administrative', 'Административный (статус / стабильность)'), ('master', 'Хозяйский (автономия / ответственность)'), ('mixed', 'Смешанный')], max_length=50, verbose_name='Тип мотивации по Герчикову'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='motivation_expect',
            field=models.TextField(blank=True, verbose_name='Что хочет сотрудник'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role_in_team',
            field=models.CharField(blank=True, max_length=100, verbose_name='Роль в команде'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_block',
            field=models.JSONField(blank=True, help_text='{"min": 150000, "motivation": "премии", "development": "обучение"}', null=True, verbose_name='Блок зарплаты'),
        ),
    ]
