# Generated by Django 3.2.16 on 2026-04-18 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20260418_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='disc_scores',
            field=models.JSONField(blank=True, null=True, verbose_name='DISC баллы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='generation',
            field=models.CharField(blank=True, choices=[('X', 'Поколение X (1965–1980)'), ('Y', 'Поколение Y / Миллениалы (1981–1996)'), ('Z', 'Поколение Z (1997–2012)'), ('Alpha', 'Поколение Alpha (2013+)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gerchikov_type',
            field=models.CharField(blank=True, choices=[('instrumental', 'Инструментальный (деньги / результат)'), ('professional', 'Профессиональный (рост / мастерство)'), ('patriotic', 'Патриотический (причастность / команда)'), ('administrative', 'Административный (статус / стабильность)'), ('master', 'Хозяйский (автономия / ответственность)'), ('mixed', 'Смешанный')], max_length=50, verbose_name='Тип мотивации по Герчикову'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_block',
            field=models.JSONField(blank=True, null=True, verbose_name='Блок зарплаты'),
        ),
    ]
