# Generated by Django 3.2.16 on 2026-04-18 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20260418_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='teams', to='profiles.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_members', to='profiles.team'),
        ),
    ]
