# Generated by Django 3.2.16 on 2026-04-18 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_auto_20260418_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-created_at'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='current_team',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='disc_scores',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active_candidate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='motivation_expect',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary_block',
        ),
        migrations.RemoveField(
            model_name='team',
            name='employees',
        ),
        migrations.AddField(
            model_name='employee',
            name='disc_primary',
            field=models.CharField(blank=True, max_length=1, verbose_name='Доминирующий тип DISC'),
        ),
        migrations.AddField(
            model_name='employee',
            name='disc_profile',
            field=models.JSONField(blank=True, default=dict, verbose_name='DISC профиль'),
        ),
        migrations.AddField(
            model_name='employee',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='employees', to='profiles.Team'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fio',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='generation',
            field=models.CharField(blank=True, choices=[('BB', 'Бэби-бумеры (1944-1963)'), ('X', 'Поколение X (1964-1984)'), ('Y', 'Миллениалы (1985-2000)'), ('Z', 'Поколение Z (2001-2015)')], max_length=10, null=True, verbose_name='Поколение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gerchikov_type',
            field=models.CharField(blank=True, choices=[('instrumental', 'Инструментальный (деньги, бонусы)'), ('professional', 'Профессиональный (развитие, интерес)'), ('patriotic', 'Патриотический (идея, миссия)'), ('lumpen', 'Люмпенизированный (избегание)'), ('master', 'Хозяйский (ответственность, власть)')], max_length=50, null=True, verbose_name='Тип мотивации'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название команды'),
        ),
    ]
