# Generated by Django 3.2.16 on 2026-04-18 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20260418_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='disc_primary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='disc_profile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='employee',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_members', to='profiles.team'),
        ),
        migrations.AddField(
            model_name='employee',
            name='disc_scores',
            field=models.JSONField(blank=True, null=True, verbose_name='DISC баллы'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active_candidate',
            field=models.BooleanField(default=True, verbose_name='Активный кандидат'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='motivation_expect',
            field=models.TextField(blank=True, verbose_name='Что хочет сотрудник'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_block',
            field=models.JSONField(blank=True, null=True, verbose_name='Блок зарплаты'),
        ),
        migrations.AddField(
            model_name='team',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='teams', to='profiles.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(default=25, verbose_name='Возраст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='fio',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='generation',
            field=models.CharField(blank=True, choices=[('X', 'Поколение X (1965–1980)'), ('Y', 'Поколение Y / Миллениалы (1981–1996)'), ('Z', 'Поколение Z (1997–2012)'), ('Alpha', 'Поколение Alpha (2013+)')], default='X', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='gerchikov_type',
            field=models.CharField(blank=True, choices=[('instrumental', 'Инструментальный (деньги / результат)'), ('professional', 'Профессиональный (рост / мастерство)'), ('patriotic', 'Патриотический (причастность / команда)'), ('administrative', 'Административный (статус / стабильность)'), ('master', 'Хозяйский (автономия / ответственность)'), ('mixed', 'Смешанный')], default='instrumental', max_length=50, verbose_name='Тип мотивации по Герчикову'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название команды'),
        ),
    ]
